name: build
on: pull_request

jobs:
  melodic_build:
    runs-on:  ubuntu-18.04
    
    container: ros:melodic
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: rosdep update
        run: |
          apt-get update
          rosdep update

      - name: Create Workspace
        run: |
          mkdir -p ~/eagleye/src/
          cp -r `pwd` ~/eagleye/src/

      - name: Clone rtklib_msgs
        run: |
          cd ~/eagleye/src/
          git clone https://github.com/MapIV/rtklib_ros_bridge.git

      - name: Build
        run: |
          cd ~/eagleye/
          source /opt/ros/melodic/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DCMAKE_BUILD_TYPE=Release -j1

  noetic_build:
    runs-on:  ubuntu-20.04
    
    container: ros:noetic
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: rosdep update
        run: |
          apt-get update
          rosdep update

      - name: Create Workspace
        run: |
          mkdir -p ~/eagleye/src/
          cp -r `pwd` ~/eagleye/src/

      - name: Clone rtklib_msgs
        run: |
          cd ~/eagleye/src/
          apt-get install git -y
          git clone https://github.com/MapIV/rtklib_ros_bridge.git

      - name: Build
        run: |
          cd ~/eagleye/
          source /opt/ros/noetic/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DCMAKE_BUILD_TYPE=Release -j1
